name: zkevm-chain
on:
  workflow_dispatch:
  repository_dispatch:
    types: [zkevm-chain]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  main:
    timeout-minutes: 5
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      AWS_DEFAULT_REGION: ap-south-1
      IMAGE_ID: ami-0a60600ebca79fab3
      KEY_NAME: pinkie
      SUBNET_ID: subnet-005b28c6bd85faa5c
      SECURITY_GROUP_ID: sg-0ec6bb25610783aeb
      REPO: privacy-scaling-explorations/zkevm-chain
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
      - run: ./run.sh
